import serialize from 'serialize-javascript';
export default function (_a) {
    var helmet = _a.helmet, cssMarkup = _a.cssMarkup, styles = _a.styles, scripts = _a.scripts, root = _a.root, initialState = _a.initialState, asyncState = _a.asyncState, gaTrackingId = _a.gaTrackingId;
    return "\n<!DOCTYPE html>\n<html lang=\"de\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width,minimum-scale=1,initial-scale=1\">\n    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n    <meta http-equiv=\"Content-Language\" content=\"de\" />\n    <link rel=\"mask-icon\" href=\"/safari-pinned-tab.svg\" color=\"#FBA139\">\n    <link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/apple-icon-57x57.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/apple-icon-60x60.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/apple-icon-72x72.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/apple-icon-76x76.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/apple-icon-114x114.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/apple-icon-120x120.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/apple-icon-144x144.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/apple-icon-152x152.png\">\n    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-icon-180x180.png\">\n    <link rel=\"icon\" type=\"image/png\" sizes=\"192x192\" href=\"/android-icon-192x192.png\">\n    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/favicon-32x32.png\">\n    <link rel=\"icon\" type=\"image/png\" sizes=\"96x96\" href=\"/favicon-96x96.png\">\n    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/favicon-16x16.png\">\n    <link rel=\"manifest\" href=\"/manifest.json\">\n    <link rel=\"apple-touch-startup-image\" href=\"/launch.png\">\n    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n    <meta name=\"msapplication-TileColor\" content=\"#FBA139\">\n    <meta name=\"msapplication-TileImage\" content=\"/ms-icon-144x144.png\">\n    <meta name=\"theme-color\" content=\"#FBA139\">\n    " + helmet.title.toString() + "\n    " + helmet.meta.toString() + "\n    " + helmet.link.toString() + "\n    " + styles.map(function (style) {
        return "<link rel=\"stylesheet\" type=\"text/css\" href=\"" + style + "\" media=\"none\" onload=\"if(media!='all')media='all'\">";
    }) + "\n    " + styles.map(function (style) { return "<noscript><link rel=\"stylesheet\" href=\"" + style + "\"></noscript>"; }) + "\n    <style id=\"css-markup\">" + (cssMarkup || '') + "</style>\n    " + (gaTrackingId
        ? "<script type=\"text/javascript\">\n      var gaProperty = '" + gaTrackingId + "';\n      var disableStr = 'ga-disable-' + gaProperty;\n      if (document.cookie.indexOf(disableStr + '=true') > -1) {\n      window[disableStr] = true;\n      }\n      function gaOptout() {\n        document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';\n        window[disableStr] = true;\n      }\n    </script>\n    <script>\n      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n      ga('create', '" + gaTrackingId + "', 'auto');\n      ga('send', 'pageview');\n    </script>"
        : '') + "\n  </head>\n  <body>\n    <div id=\"app\"><div>" + root + "</div></div>\n    <script type='text/javascript'>window.INITIAL_DATA=" + serialize(initialState) + "</script>\n    <script type='text/javascript'>window.ASYNC_STATE=" + serialize(asyncState) + "</script>\n    <script type='text/javascript'>function POLY() { window.POLYFILLED = true; if (window.GO) window.GO(); }</script>\n    <script async src=\"https://cdn.polyfill.io/v2/polyfill.min.js?callback=POLY\"></script>\n    " + scripts.map(function (script) { return "<script async src=\"" + script + "\"></script>"; }) + "\n  </body>\n</html>\n";
};
//# sourceMappingURL=default.js.map