service: serverless-graphql

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: eu-west-1
  environment: ${file(env.yml):${self:provider.stage}}

plugins:
  - serverless-offline

functions:
  graphql:
    handler: handler.server
    events:
    - http:
        path: graphql
        method: post
        cors: true
  playground:
    handler: handler.playground
    events:
    - http:
        path: graphql
        method: get
        cors: true